# Generated by Django 5.0.7 on 2024-07-20 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='наименование')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/course_image/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'db_table': 'course',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='наименование')),
                ('slug', models.CharField(max_length=120, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/lesson_image/', verbose_name='изображение')),
                ('link_video', models.FileField(blank=True, null=True, upload_to='media/lesson_video', verbose_name='видео')),
                ('name_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='урок', to='materials.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'db_table': 'lesson',
                'ordering': ('name', 'name_course'),
            },
        ),
    ]
