# Generated by Django 5.0.7 on 2024-07-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120, verbose_name='наименование курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=120, unique=True, verbose_name='имя слаг'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=120, verbose_name='наименование урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='урок', to='materials.course', verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.CharField(max_length=120, unique=True, verbose_name='имя слаг'),
        ),
    ]
